version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/ruby:latest'
    steps:
      - checkout
      - run:
          name: Run Gem build
          command: gem build scryfall
  test:
    docker:
      - image: 'circleci/ruby:latest'
    steps:
      - checkout
      - run:
          name: Installing Gems
          command: gem install rspec http
      - run:
          name: Run Tests
          command: rspec
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test
