version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/ruby:latest'
    steps:
      - checkout
      - run:
        name: Run Gem build
        command: gem build scryfall.gemspec
  test:
    docker:
      - image: 'circleci/ruby:latest'
    steps:
      - checkout
      - run:
          name: Which Bundle?
          command: bundle -v
workflows:
  version: 2
  test-deploy:
    jobs:
      - build
      - test
